### ISSUE TITLE
configure-env document says SAML instead of UAA

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [pivotal/docs-platform-automation#20]
**URL or GitHub link to the page where you're having the issue**
Where in the documentation set can I see the problem? If it's a more general request, then at least identify the product and version. 

https://docs.pivotal.io/platform-automation/v3.0/configuration-management/configure-env.html#generating-an-env-file 

**Is your request for a change or addition to content related to a problem? If so, please describe.**
The documentation for using UAA authentication says "SAML" authentication

**Describe the solution you'd like**
It should say UAA authentication

**Describe alternatives you've considered**
n/a

**Additional context**
See the difference between the two links:
* https://docs.pivotal.io/platform-automation/v3.0/configuration-management/configure-env.html#generating-an-env-file
* https://docs.pivotal.io/platform-automation/v3.0/reference/inputs-outputs.html#uaa-authentication

**Comment by anEXPer** [comment]
I don't think it should say "UAA," but I do think we can be clearer about what we mean here.

UAA is an implementation detail; the reason someone would need to use client_id and client_secret is if they've configured authentication to use a SAML or LDAP service for their users, and thus can't necessarily simply provide a username and password, since the integration doesn't work that way.

So that's why it says "or, if using SAML" right now.

How would you feel about the sentence being reworked thusly:

`or, if using SAML, a client-id and client-secret.` > `If you've configured an external user store, you may need or prefer to use a client you've created (or Ops Manager has created for you) in the Ops Manager UAA. In this case, you'll need to use client-id and client-secret instead of username and password.`

**Comment by anEXPer** [comment]
I took a crack at clarifying the situation, but it was a more substantial edit than the one I describedd above. You can see it [here](https://docs-pcf-staging.cfapps.io/platform-automation/v3.0/configuration-management/configure-env.html). Lemme know what you think?

**Comment by patrick-huber-pivotal** [comment]
That looks great, thanks!

**Comment by nbconklin** [comment]
Thank you! The changes are live, closing this issue.
